module gpu_cmpdt
  use amr_parameters, only: dp
  use hydro_integrator, only: conserved_t, primitive_t
  use gpu_reduce, only: block_reduce_sum, bock_reduce_min
  use oct_commons, only: oct
  use cudafor
  implicit none

contains

  ! =========================================================================
  attributes(global) subroutine cmpdt_kernel(oct_grid, num_oct, mass, ekin, eint, emag, dt, dx, gammma)
    type(oct), device, dimension(*) :: oct_grid
    integer(kind=8), intent(in), value :: num_oct
    real(kind=8), intent(in), value :: dx, gamma
    real(kind=8), device, intent(inout) :: mass, ekin, eint, emag, dt

    type(primitive_t) :: primitive
    type(conserved_t) :: conserved
    integer :: info
    integer :: block_idx  ! The index of this block, corresponds to the oct to load
    integer :: cell_idx ! The index of the cell within the block
    integer :: oct_idx ! The index of the oct  within the block
    real(kind=8) :: vol_loc, mass_loc, ekin_loc, eint_loc, emag_loc, dt_loc
    real(kind=8) :: sound_speed

    block_idx = blockIdx%x - 1

    ! Compute the oct idx
    oct_idx = block_idx * blockDim%y + threadIdx%y
    if (oct_idx > num_oct) return

    ! Compute the cell idx
    cell_idx = threadIdx%x

    ! Load the cell
    conserved%density    = oct_grid(oct_idx)%uold(cell_idx, 1)
    conserved%momentum_x = oct_grid(oct_idx)%uold(cell_idx, 2)
    conserved%momentum_y = oct_grid(oct_idx)%uold(cell_idx, 3)
    conserved%momentum_z = oct_grid(oct_idx)%uold(cell_idx, 4)
    conserved%energy     = oct_grid(oct_idx)%uold(cell_idx, 5)

    ! Convert to primitive variables
    primitive = conserved_2_primitive(conserved, gamma)

    ! Compute extensive quantities
    vol_loc = dx*dx*dx
    mass_loc = primitive%density*vol_loc
    ekin_loc = conserved%energy*vol_loc
    eint_loc = primitive%pressure/(gamma-1d0)*vol_loc
    emag_loc = 0d0

    ! Compute time step
    sound_speed = sqrt(gamma*primitive%pressure/primitive%density)
    dt_loc = dx / (abs(primitive%velocity_x)+abs(primitive%velocity_y)+abs(primitive%velocity_z)+3*sound_speed)

    dt_loc = block_reduce_min(dt_loc)
    mass_loc = block_reduce_sum(mass_loc)
    ekin_loc = block_reduce_sum(ekin_loc)
    eint_loc = block_reduce_sum(eint_loc)
    emag_loc = block_reduce_sum(emag_loc)

    if(threadIdx%x==1 .and. threadIdx%y==1)then
       info = atomicmin(dt,dt_loc)
       info = atomicadd(mass,mass_loc)
       info = atomicadd(ekin,ekin_loc)
       info = atomicadd(eint,eint_loc)
       info = atomicadd(emag,emag_loc)
    endif

  end subroutine cmpdt_kernel
  ! =========================================================================

end module gpu_cmpdt

