module gpu_runner
  use amr_parameters, only: ndim, twotondim, threetondim, dp
  use, intrinsic :: iso_c_binding, only: C_PTR
  use gpu_utils
  use cudafor
  use oct_commons, only: oct
  implicit none
  integer, dimension(1:3), parameter::n_nbor = (/1,2,2/)

  type hash_gpu
     integer(kind=4) :: size, used
     integer(kind=8), allocatable, dimension(:) :: key
     integer(kind=4), allocatable, dimension(:) :: val
  end type hash_gpu

  type mesh_gpu

     integer(kind=4) :: ngridmax, ncachemax

     logical, dimension(1:3) :: periodic
     integer(kind=4), allocatable, dimension(:) :: ckey_max
     integer(kind=8), allocatable, dimension(:) :: key_off
     integer(kind=4), allocatable, dimension(:,:) :: box_ckey_min
     integer(kind=4), allocatable, dimension(:,:) :: box_ckey_max
     integer(kind=4), allocatable, dimension(:,:,:) :: bound_ckey_min
     integer(kind=4), allocatable, dimension(:,:,:) :: bound_ckey_max

     integer(kind=4), allocatable, dimension(:) :: head
     integer(kind=4), allocatable, dimension(:) :: tail
     integer(kind=4), allocatable, dimension(:) :: noct
     integer(kind=4) :: ifree

     integer(kind=4), allocatable, dimension(:) :: head_cache
     integer(kind=4), allocatable, dimension(:) :: tail_cache
     integer(kind=4), allocatable, dimension(:) :: noct_cache
     integer(kind=4) :: ifree_cache

     type(oct), allocatable, dimension(:) :: grid

     integer(kind=4), allocatable, dimension(:) :: father
     integer(kind=4), allocatable, dimension(:,:) :: nbor

     integer(kind=4), allocatable, dimension(:,:) :: flag1, flag2
     real(kind=dp), allocatable, dimension(:,:,:) :: uold, unew

     integer(kind=4), allocatable, dimension(:) :: swap_local
     integer(kind=4), allocatable, dimension(:) :: swap_global
     integer(kind=4), allocatable, dimension(:) :: prefix_sum
     integer(kind=4), allocatable, dimension(:) :: partial_sums_0
     integer(kind=4), allocatable, dimension(:) :: partial_sums_1

     type(hash_gpu) :: hash

  end type mesh_gpu

  !> Object to hold the grid and the hash table on the device
  type(mesh_gpu), device :: mesh_device

  !> The Fortran array of hydro variables of ghost and halo octs on the host and the C_PTR to it
  real(kind=dp), pointer, dimension(:) :: uold_send_host, uold_recv_host
  type(C_PTR) :: uold_send_host_cptr, uold_recv_host_cptr

  !> The Fortran array of hydro variables of ghost and halo octs on the device and the C_PTR to it
  real(kind=dp), device, pointer, dimension(:) :: uold_send_device, uold_recv_device
  type(C_DEVPTR) :: uold_send_device_cptr, uold_recv_device_cptr

  !> The Fortran array of oct index of ghost and halo octs on the host and the C_PTR to it
  integer, pointer, dimension(:) :: idx_send_host, idx_recv_host
  type(C_PTR) :: idx_send_host_cptr, idx_recv_host_cptr

  !> The Fortran array of oct index of ghost and halo octs on the device and the C_PTR to it
  integer, device, pointer, dimension(:) :: idx_send_device, idx_recv_device
  type(C_DEVPTR) :: idx_send_device_cptr, idx_recv_device_cptr

  !> The Fortran array of the hash keys of ghost and halo octs on the host only
  integer, allocatable, dimension(:) :: key_send_host, key_recv_host

  !> The number of halo and ghost octs per cpu
  integer, allocatable, dimension(:) :: n_send, n_recv

  !> The total number of halo and ghost octs
  integer(kind=4) :: num_send, num_recv

contains

  include 'scan.cuf'

  !> @brief
  !> Compute the new time step on a GPU
  !>
  !> @detail
  !> @param[in] sim : The simulation object
  !> @param[in] ilevel : The refinement level to update
  !>
  subroutine gpu_cmpdt(sim, ilevel, mass, ekin, eint, emag, dt)
    use nvtx
    use hydro_device, only: cmpdt_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout) :: sim
    integer, intent(in) :: ilevel
    real(kind=8), intent(inout) :: mass, ekin, eint, emag, dt

    integer(kind=4) :: head_idx, num_octs
    integer :: num_threads, num_blocks
    real(kind=dp) :: gamma, dx
    real(kind=8), device :: mass_d, ekin_d, eint_d, emag_d, dt_d

    gamma = sim%r%gamma
    dx = sim%r%boxlen/2**ilevel
    dt = dx/sim%r%smallc

    ! host to device
    dt_d = dt
    mass_d = 0d0
    ekin_d = 0d0
    eint_d = 0d0
    emag_d = 0d0

    head_idx = mesh_device%head(ilevel)
    num_octs = mesh_device%noct(ilevel)
    num_threads = 1024
    num_blocks = (num_octs * twotondim + num_threads - 1 ) / num_threads
    call nvtxStartRange("GPU cmpdt", color=0)!green
    call cmpdt_kernel<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs, mass_d, ekin_d, eint_d, emag_d, dt_d, dx, gamma)
    call GPU_Error_Check(__FILE__, __LINE__)
    call nvtxEndRange()

    ! device to host
    dt = dt_d
    mass = mass_d
    ekin = ekin_d
    eint = eint_d
    emag = emag_d

  end subroutine gpu_cmpdt

  !> @brief
  !> Set uold equal to unew on a GPU
  !>
  !> @detail
  !> @param[in] sim : The simulation object
  !> @param[in] ilevel : The refinement level to update
  !>
  subroutine gpu_set_uold(sim, ilevel)
    use nvtx
    use hydro_device, only: set_uold_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    integer, intent(in)::ilevel

    integer(kind=4) :: head_idx, num_octs
    integer :: err_code, threadsX_per_block, threadsY_per_block, num_blocks

    head_idx = mesh_device%head(ilevel)
    num_octs = mesh_device%noct(ilevel)
    threadsX_per_block = 8
    threadsY_per_block = 16
    num_blocks = (num_octs + threadsY_per_block - 1) / threadsY_per_block
    call nvtxStartRange("GPU Set_uold", color=0)!green
    call set_uold_kernel<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(mesh_device, head_idx, num_octs)
    call GPU_Error_Check(__FILE__, __LINE__)
    call nvtxEndRange()

  end subroutine gpu_set_uold

  !> @brief
  !> Set unew equal to uold on a GPU
  !>
  !> @detail
  !> @param[in] sim : The simulation object
  !> @param[in] ilevel : The refinement level to update
  !>
  subroutine gpu_set_unew(sim, ilevel)
    use nvtx
    use hydro_device, only: set_unew_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    integer, intent(in)::ilevel

    integer(kind=4) :: head_idx, num_octs
    integer :: err_code, threadsX_per_block, threadsY_per_block, num_blocks

    head_idx = mesh_device%head(ilevel)
    num_octs = mesh_device%noct(ilevel)
    threadsX_per_block = 8
    threadsY_per_block = 16
    num_blocks = (num_octs + threadsY_per_block - 1) / threadsY_per_block
    call nvtxStartRange("GPU Set_unew", color=0)!green
    call set_unew_kernel<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(mesh_device, head_idx, num_octs)
    call GPU_Error_Check(__FILE__, __LINE__)
    call nvtxEndRange()

  end subroutine gpu_set_unew

  !> @brief
  !> Perform the hydro integration on a GPU
  !>
  !> @detail
  !> Perform the hydro integration on the GPU with the following steps
  !>
  !> @param[in] sim : The simulation object
  !> @param[in] ilevel : The refinement level to update
  !>
  subroutine gpu_godunov(sim, ilevel)
    use nvtx
    use hydro_device, only: hydro_integrator_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    integer, intent(in)::ilevel
    !
    integer(kind=4) :: head_idx, num_octs
    integer :: err_code, threads_per_block, num_blocks, subgrid_size
    real(dp) :: dt, dx, gamma

    head_idx = mesh_device%head(ilevel)
    num_octs = mesh_device%noct(ilevel)
    dt = sim%g%dtnew(ilevel)
    dx = sim%r%boxlen/2**ilevel
    gamma = sim%r%gamma
    num_blocks = num_octs
    threads_per_block = 128
    subgrid_size = 6

    call nvtxStartRange("GPU Godunov", color=0)!green
    call hydro_integrator_kernel<<<num_blocks, threads_per_block>>>(mesh_device, head_idx, num_octs, subgrid_size, gamma, dt/dx)
    call GPU_Error_Check(__FILE__, __LINE__)
    call nvtxEndRange()

  end subroutine gpu_godunov

  !> @brief
  !> Restriction of fine cells hydro variable into the coarse level
  !>
  !> @detail
  !> Average conservatively the 8 fine children cells hydro variables into the parent coarse cell.
  !>
  !> @param[in] sim : The simulation object
  !> @param[in] ilevel : The refinement level to update
  !>
  subroutine gpu_upload(sim, ilevel)
    use nvtx
    use hydro_device, only: upload_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    integer, intent(in)::ilevel
    !
    integer(kind=4) :: head_idx, num_octs
    integer :: err_code, threads_per_block, num_blocks

    head_idx = mesh_device%head(ilevel)
    num_octs = mesh_device%noct(ilevel)
    num_blocks = num_octs
    threads_per_block = 128

    call nvtxStartRange("GPU Godunov", color=0)!green
    call upload_kernel<<<num_blocks, threads_per_block>>>(mesh_device, head_idx, num_octs)
    call GPU_Error_Check(__FILE__, __LINE__)
    call nvtxEndRange()

  end subroutine gpu_upload

  !> @brief
  !> Perform the hydro integration on a GPU
  !>
  !> @detail
  !> Perform the hydro integration on the GPU with the following steps
  !>
  !> @param[in] sim : The simulation object
  !> @param[in] ilevel : The refinement level to update
  !>
  subroutine gpu_refine(sim, ilevel)
    use nvtx
    use refine_device
    use ramses_commons, only: ramses_t
    use cache_commons
    use cache
    type(ramses_t), intent(inout)::sim
    integer, intent(in)::ilevel
    !
    integer(kind=4) :: head_idx, num_octs, num_threads
    integer(kind=4) :: num_blocks, threadsX_per_block, threadsY_per_block
    integer(kind=4) :: ifree, new_ifree, old_ifree, new_head, new_tail, new_noct
    integer(kind=4) :: ilev, ind, ibit, ibucket, skip_bit, noct_level, num_ones
    integer(kind=4) :: used, size
    real(kind=8)    :: filling

    ! Wipe clean cache memory hash entries for all higher levels
    head_cache = mesh_device%head_cache(ilevel + 1)
    old_ifree = mesh_device%ifree_cache
    num_octs = old_ifree - head_cache
    head_idx = head_cache + sim%r%ngridmax
    num_threads = 128
    num_blocks = (num_octs + num_threads - 1) / num_threads
    if (num_octs > 0) then
       call free_hash_kernel<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)
    endif

    ! Remove old octs by setting lev to zero and free the hash table 
    head_idx = mesh_device%head(ilevel+1)
    old_ifree = mesh_device%ifree
    num_octs = old_ifree - head_idx
    num_threads = 128
    num_blocks = (num_octs + num_threads - 1) / num_threads
    if (num_octs > 0) then
       call derefine_kernel<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)
    endif

    ! Create new octs and put them at the end
    head_idx = mesh_device%head(ilevel)
    old_ifree = mesh_device%ifree
    num_octs = old_ifree - head_idx
    threadsX_per_block = 8
    threadsY_per_block = 16
    num_blocks = (num_octs + threadsY_per_block - 1) / threadsY_per_block
    if (num_octs > 0) then
       call refine_kernel<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(mesh_device, head_idx, num_octs)
    endif
    new_ifree = mesh_device%ifree

    ! Check we have enough memory
    if (new_ifree > sim%r%ngridmax) then
       write(*,*)'No more main memory, increase ngridmax'
    endif

    ! If hash is full, wipe it clean and rehash mesh
    used = mesh_device%hash%used
    size = mesh_device%hash%size
    used = used + new_ifree - old_ifree
    filling = dble(used) / dble(size)
    if (filling > 0.6) then
       write(*,*)'Removing hash tombstones...'
       call gpu_reset_hash(sim)
    else
       ! Insert new octs in hash table
       head_idx = old_ifree
       num_octs = new_ifree - old_ifree
       num_threads = 128
       num_blocks = (num_octs + num_threads - 1) / num_threads
       if (num_octs > 0) then
          call insert_hash_kernel<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)
       end if
    end if

    ! Sort remaining octs per level and per Hilbert key

    ! Compute kernel size and offset
    head_idx = mesh_device%head(ilevel + 1)
    num_octs = new_ifree - head_idx
    num_threads = 128
    num_blocks = (num_octs + num_threads - 1) / num_threads

    ! Init global swap table
    if (num_octs > 0) then
       call init_global_swap_table_kernel<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)
    endif

    ! Sort octs per levels

    ! Compute new head
    new_head = mesh_device%tail(ilevel)
    new_head = new_head + 1

    do ilev = ilevel + 1, sim%r%nlevelmax

       ! Transfer new head
       mesh_device%head(ilev) = new_head

       ! Compute kernel size and offset
       head_idx = mesh_device%head(ilev)
       num_octs = new_ifree - head_idx
       num_threads = 128
       num_blocks = (num_octs + num_threads - 1) / num_threads

       new_noct = 0

       if (num_octs > 0) then

          ! Init prefix sum
          call init_prefix_sum_level<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs, ilev)

          ! Compute prefix sum
          call gpu_scan(mesh_device, head_idx, num_octs)

          ! Compute new noct
          num_ones = mesh_device%prefix_sum(head_idx + num_octs - 1)
          new_noct = num_octs - num_ones

          ! Compute local swap table
          call compute_local_swap_table<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)

          ! Update global swap table
          call update_global_swap_table<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)

       endif

       ! Compute new tail and next head
       new_tail = new_head + new_noct - 1
       new_head = new_tail + 1
       mesh_device%noct(ilev) = new_noct
       mesh_device%tail(ilev) = new_tail

       ! Transfer head, tail and noct to host
       sim%m%head(ilev) = mesh_device%head(ilev)
       sim%m%tail(ilev) = mesh_device%head(ilev)
       sim%m%noct(ilev) = mesh_device%head(ilev)

    end do

    ! New pointer to free memory
    mesh_device%ifree = new_head
    sim%m%ifree = new_head

    ! Sort Hilbert key within each level
    do ilev = ilevel + 1, sim%r%nlevelmax

       noct_level = mesh_device%noct(ilev)

       if (noct_level > 0) then

          do ibit = ilev, 1, -1

             ! Get bit to read from
             skip_bit = ndim*(ilev-ibit)

             ! Compute kernel size and offset
             new_head = mesh_device%head(ilev)
             new_noct = noct_level

             ! loop over buckets
             do ibucket = 1, twotondim - 1

                ! Compute kernel size and offset
                head_idx = new_head
                num_octs = new_noct
                num_threads = 128
                num_blocks = (num_octs + num_threads - 1) / num_threads

                if (num_octs > 0) then

                   ! Init prefix sum
                   call init_prefix_sum_bit<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs, &
                        &               skip_bit, ibucket - 1)

                   ! Compute prefix sum
                   call gpu_scan(mesh_device, head_idx, num_octs)

                   ! Compute local swap table
                   call compute_local_swap_table<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)

                   ! Update global swap table
                   call update_global_swap_table<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)

                   ! Compute new head and noct
                   new_noct = mesh_device%prefix_sum(new_head + new_noct - 1)
                   new_head = head_idx + num_octs - new_noct

                endif

             end do
          end do
       endif
    end do

    ! Compute kernel size and offset
    head_idx = mesh_device%head(ilevel + 1)
    new_ifree = mesh_device%ifree
    num_octs = new_ifree - head_idx
    num_threads = 128
    num_blocks = (num_octs + num_threads - 1) / num_threads

    ! Out-of-place sort of grid, flag1 and uold using swap table
    if (num_octs > 0) then
       call sort_gather_grid<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)
       call sort_scatter_grid<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)
       call sort_gather_flag<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)
       call sort_scatter_flag<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)
       call sort_gather_hydro<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)
       call sort_scatter_hydro<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)
    endif

    ! Update hash table
    if (num_octs > 0) then
       call update_hash_kernel<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)
    end if

    ! Update father index array (they should always exist without MPI)
    if (num_octs > 0) then
       call update_father_array<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)
    endif

    ! Update nbor index array level by level
    ! If nbor is absent, make a ghost oct in the cache and insert in hash table

    ! Compute new cache head
    new_head = mesh_device%tail_cache(ilevel)
    new_head = new_head + 1

    do ilev = ilevel + 1, sim%r%nlevelmax

       noct_level = mesh_device%noct(ilev)
       mesh_device%head_cache(ilev) = new_head

       new_noct = 0

       if (noct_level > 0) then

          ! Compute kernel size and offset
          head_idx = mesh_device%head(ilev)
          num_noct = noct_level

          ! Loop over 27 neighbors
          do ind = 1, threetondim

             ! Get nbor index from hash table
             call update_nbor_array<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs, ind)

             ! Init prefix sum (count non existing nbor index)
             call init_prefix_sum_nbor<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs, ind)

             ! Compute prefix sum
             call gpu_scan(mesh_device, head_idx, num_octs)

             ! Compute number of new ghost octs
             new_noct = mesh_device%prefix_sum(head_idx + num_octs - 1)

             ! Transfer head index of first free cache oct from device
             ifree_cache = mesh_device%ifree_cache
             head_cache = sim%r%ngridmax + ifree_cache
             new_ifree = ifree_cache + new_noct

             if (new_noct > 0) then

                ! Check we have enough memory
                if (new_ifree > sim%r%ncachemax) then
                   write(*,*)'No more cache memory, increase ncachemax'
                   stop
                endif

                ! Compute cache swap table
                call compute_cache_swap_table<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_octs)

                ! Compute kernel size and offset
                num_threads = 128
                num_blocks = (new_noct + num_threads - 1) / num_threads

                ! Make new ghost octs in cache
                call make_cache_octs<<<num_blocks, num_threads>>>(mesh_device, head_cache, new_noct, ind)

                ! Insert new octs in hash table
                call insert_hash_kernel<<<num_blocks, num_threads>>>(mesh_device, head_cache, new_noct)

             end if

             ! Store new first free cache oct back on device
             ifree_cache = new_ifree
             mesh_device%ifree_cache = ifree_cache

          end do
          ! End loop over 27 nbors

       end if

       ! Compute new cache tail and next cache head
       new_tail = new_head + new_noct - 1
       new_head = new_tail + 1
       mesh_device%noct_cache(ilev) = new_noct
       mesh_device%tail_cache(ilev) = new_tail

    end do
    ! End loop over levels

  end subroutine gpu_refine

  !> @brief
  !> Initial step for flagging cells for refinements
  !>
  !> @detail
  !> A cell is flag if it contains a child grid with at least one flagged or refined cell
  !>
  subroutine gpu_init_flag(sim, ilevel)
    use nvtx
    use hydro_device, only: set_uold_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    integer, intent(in)::ilevel

    integer(kind=4) :: head_idx, num_octs
    integer :: threadsX_per_block, threadsY_per_block, num_threads, num_blocks

    head_idx = mesh_device%head(ilevel)
    num_octs = mesh_device%noct(ilevel)
    threadsX_per_block = 8
    threadsY_per_block = 16
    num_blocks = (num_octs + threadsY_per_block - 1) / threadsY_per_block
    if(num_octs > 0)then
       call reset_flag1_kernel<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(mesh_device, head_idx, num_octs)
    endif

    head_idx = mesh_device%head(ilevel+1)
    num_octs = mesh_device%noct(ilevel+1)
    num_threads = 128
    num_blocks = (num_oct + num_threads - 1) / num_threads
    if(num_octs > 0)then
       call init_flag_kernel<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_oct)
    endif

  end subroutine gpu_init_flag

  !> @brief
  !> User defined refinement criteria
  !>
  !> @detail
  !> Apply several user-defined refinement criteria to flag cells
  !>
  subroutine gpu_user_flag(sim, ilevel)
    use nvtx
    use hydro_device, only: set_uold_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    integer, intent(in)::ilevel

    integer(kind=4) :: head_idx, num_octs
    integer :: threadsX_per_block, threadsY_per_block, num_threads, num_blocks, subgrid_size
    real(kind=8) :: gamma, err_grad_d, err_grad_p, floor_d, floor_p

    subgrid_size = 6
    gamma = sim%r%gamma
    err_grad_d = sim%r%err_grad_d
    err_grad_p = sim%r%err_grad_p
    floor_d = sim%r%floor_d
    floor_p = sim%r%floor_p

    head_idx = mesh_device%head(ilevel)
    num_octs = mesh_device%noct(ilevel)
    num_threads = 128
    num_blocks = (num_oct + num_threads - 1) / num_threads
    if(num_octs > 0)then
       call hydro_flag_kernel<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_oct, subgrid_size, &
            & gamma, err_grad_d, err_grad_p, floor_d, floor_p)
    endif

  end subroutine gpu_user_flag

  !> @brief
  !> Smooth refinement map
  !>
  !> @detail
  !> Set flag2 to zero, count neighbors in flag2 and set flag1 to 1 if enough neighbors.
  !>
  subroutine gpu_smooth_flag(sim, ilevel)
    use nvtx
    use hydro_device, only: set_uold_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    integer, intent(in)::ilevel

    integer(kind=4) :: head_idx, num_octs
    integer :: threadsX_per_block, threadsY_per_block, num_threads, num_blocks

    head_idx = mesh_device%head(ilevel)
    num_octs = mesh_device%noct(ilevel)
    threadsX_per_block = 8
    threadsY_per_block = 16
    num_blocks = (num_octs + threadsY_per_block - 1) / threadsY_per_block

    if(num_octs > 0)then
       do idim = 1, ndim ! Loop over steps
          call reset_flag2_kernel<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(mesh_device, head_idx, num_octs)
          call count_neighbors<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(mesh_device, head_idx, num_oct)
          call flag_count_kernel<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(mesh_device, head_idx, num_octs, n_nbor(idim))
       end do
    endif

  end subroutine gpu_smooth_flag

  !> @brief
  !> Enforce refinemnt rules
  !>
  !> @detail
  !> Set flag1 to zero if not enough existing neighboring grids
  !>
  subroutine gpu_enforce_rules(sim, ilevel)
    use nvtx
    use hydro_device, only: set_uold_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    integer, intent(in)::ilevel

    integer(kind=4) :: head_idx, num_octs
    integer :: num_threads, num_blocks

    head_idx = mesh_device%head(ilevel)
    num_octs = mesh_device%noct(ilevel)

    num_threads = 128
    num_blocks = (num_oct + num_threads - 1) / num_threads
    if(num_octs > 0)then
       call enforce_rules<<<num_blocks, num_threads>>>(mesh_device, head_idx, num_oct)
    endif

  end subroutine gpu_enforce_rules

  !> @brief
  !> Perform a prefix sum (or a scan) on the input integer array data
  !>
  !> @detail
  !> Perform a prefix scum only starting from index head_idx and over num_octs elements.
  !>
  subroutine gpu_scan(mesh, head_idx, num_octs)
    type(mesh_gpu), device :: mesh
    integer(kind=4), value :: head_idx
    integer(kind=4), value :: num_octs
    !
    integer(kind=4) :: block_size, grid_size_0, grid_size_1, grid_size_2
    integer(kind=4) :: offset, size, num_ones
    integer(kind=4) :: num_max_0, num_max_1, num_max_2

    block_size = 256
    num_max_0 = block_size**2
    num_max_1 = block_size**3
    num_max_2 = huge(1_4)

    if(num_octs <= num_max_0)then

       ! Works only for arrray size smaller or equal than 256^2=65536
       grid_size_0 = (num_octs + block_size - 1) / block_size
       call block_scan<<<grid_size_0, block_size>>>(mesh%prefix_sum, head_idx, num_octs, mesh%partial_sums_0)
       if (grid_size_0 > 1) then
          call block_scan<<<1, grid_size_0>>>(mesh%partial_sums_0, 1, grid_size_0)
          offset = head_idx + block_size
          size = num_octs - block_size
          call uniform_add<<<grid_size_0 - 1, block_size>>>(mesh%prefix_sum, offset, size, mesh%partial_sums_0)
       end if

    else if(num_octs <= num_max_1)then

       ! Works only for arrray size smaller or equal than 256^3=16777216
       grid_size_0 = (num_octs + block_size - 1) / block_size
       call block_scan<<<grid_size_0, block_size>>>(mesh%prefix_sum, head_idx, num_octs, mesh%partial_sums_0)
       grid_size_1 = (grid_size_0 + block_size - 1) / block_size
       call block_scan<<<grid_size_1, block_size>>>(mesh%partial_sums_0, 1, grid_size_1, mesh%partial_sums_1)
       if (grid_size_1 > 1) then
          call block_scan<<<1, grid_size_1>>>(mesh%partial_sums_1, 1, grid_size_1)
          offset = 1 + block_size
          size = grid_size_0 - block_size
          call uniform_add<<<grid_size_1 - 1, block_size>>>(mesh%partial_sums_0, offset, size, mesh%partial_sums_1)
       end if
       offset = head_idx + block_size
       size = num_octs - block_size
       call uniform_add<<<grid_size_0 - 1, block_size>>>(mesh%prefix_sum, offset, size, mesh%partial_sums_0)

    else if(num_octs <= num_max_2)then

       write(*,*)'Prefix sum for that many elements not yet implemented.'

       stop
    else

       write(*,*)'Too many octs for prefix sum.'
       stop

    endif

  end subroutine gpu_scan

  !> @brief
  !> Initialize the hash table
  !>
  !> @detail
  !> Loop over all existing octs and insert them in the hash table
  !>
  !> @param[in] sim : The simulation object
  !>
  subroutine gpu_reset_hash(sim)
    use nvtx
    use refine_device, only: insert_hash_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    !
    integer(kind=4) :: head_idx, num_octs
    integer :: num_blocks, threads_per_block
    integer :: size, used

    ! Allocate hash tables for the first time
    if(allocated(mesh_device%hash%key))deallocate(mesh_device%hash%key)
    if(allocated(mesh_device%hash%val))deallocate(mesh_device%hash%val)
    size = 2*(sim%r%ngridmax+sim%r%ncachemax)
    used = sim%m%ifree - 1 + sim%m%ifree_cache - 1
    mesh_device%hash%size = size
    mesh_device%hash%used = used
    allocate(mesh_device%hash%key(1:size))
    allocate(mesh_device%hash%val(1:size))
    mesh_device%hash%key = 0
    mesh_device%hash%val = 0

    ! Insert entire grid in the device hash table
    head_idx = 1
    num_octs = sim%m%ifree - 1
    if (num_octs > 0) then
       threads_per_block = 128
       num_blocks = (num_octs + threads_per_block - 1) / threads_per_block
       call insert_hash_kernel<<<num_blocks, threads_per_block>>>(mesh_device, head_idx, num_octs)
    endif

    ! Insert entire cache in the device hash table
    head_idx = sum%r%ngridmax + 1
    num_octs = sim%m%ifree_cache - 1
    if (num_octs > 0) then
       threads_per_block = 128
       num_blocks = (num_octs + threads_per_block - 1) / threads_per_block
       call insert_hash_kernel<<<num_blocks, threads_per_block>>>(mesh_device, head_idx, num_octs)
    endif

  end subroutine gpu_reset_hash

  !###########################################################
  !###########################################################
  !###########################################################
  !###########################################################

end module gpu_runner
