module gpu_runner
  use amr_parameters, only: ndim, twotondim, dp
  use oct_commons, only: oct
  use gpu_utils
  use cudafor
  implicit none
  integer, dimension(1:3), parameter::n_nbor = (/1,2,2/)

  !> Various parameters on the device
  logical, device, dimension(1:3) :: periodic   
  integer(kind=4), device, allocatable, dimension(:) :: ckey_max
  integer(kind=8), device, allocatable, dimension(:) :: key_off
  integer(kind=4), device, allocatable, dimension(:,:) :: box_ckey_min
  integer(kind=4), device, allocatable, dimension(:,:) :: box_ckey_max
  integer(kind=4), device, allocatable, dimension(:,:,:) :: bound_ckey_min
  integer(kind=4), device, allocatable, dimension(:,:,:) :: bound_ckey_max

  !> Arrays to hold the grid on the device
  type(oct), device, allocatable, dimension(:) :: grid

  integer(kind=4), device, allocatable, dimension(:) :: father
  integer(kind=4), device, allocatable, dimension(:,:) :: nbor
  integer(kind=4), device, allocatable, dimension(:,:) :: flag1, flag2

#ifdef HYDRO
  real(kind=dp), device, allocatable, dimension(:,:,:) :: uold, unew
#endif

#ifdef GRAV
  real(kind=dp), device, allocatable, dimension(:,:) :: phi
  real(kind=dp), device, allocatable, dimension(:,:) :: rho
  real(kind=dp), device, allocatable, dimension(:,:) :: nref
  real(kind=dp), device, allocatable, dimension(:,:) :: phi_old
  real(kind=dp), device, allocatable, dimension(:,:,:) :: f
#endif

  integer(kind=4), device, allocatable, dimension(:) :: swap_local
  integer(kind=4), device, allocatable, dimension(:) :: swap_global

  !> Arrays to hold the hash table on the device
  integer(kind=8), device, allocatable, dimension(:) :: hash_key
  integer(kind=4), device, allocatable, dimension(:) :: hash_val

  !> Object to hold the prefix sum data vector and workspace
  integer(kind=4), device, allocatable, dimension(:) :: prefix_sum
  integer(kind=4), device, allocatable, dimension(:) :: partial_sums_0
  integer(kind=4), device, allocatable, dimension(:) :: partial_sums_1
  integer(kind=4), device, allocatable, dimension(:) :: partial_sums_2

  !> The Fortran array of hydro variables of ghost and halo octs on the host and on the device
  real(kind=dp), allocatable, dimension(:) :: uold_send_host, uold_recv_host
  real(kind=dp), device, allocatable, dimension(:) :: uold_send_device, uold_recv_device

  !> The Fortran array of oct index of ghost and halo octs on the host and the device
  integer, allocatable, dimension(:) :: idx_send_host, idx_recv_host
  integer, device, allocatable, dimension(:) :: idx_send_device, idx_recv_device

  !> The Fortran array of the hash keys of ghost and halo octs on the host only
  integer, allocatable, dimension(:) :: key_send_host, key_recv_host

  !> The number of halo and ghost octs per cpu
  integer, allocatable, dimension(:) :: n_send, n_recv

  !> The total number of halo and ghost octs
  integer(kind=4) :: num_send, num_recv

contains

  include 'gpu_scan.cuf'

  !> @brief
  !> Compute the new time step on a GPU
  !>
  !> @detail
  !> @param[in] sim : The simulation object
  !> @param[in] ilevel : The refinement level to update
  !>
  subroutine gpu_cmpdt(sim, ilevel, mass, ekin, eint, emag, dt)
    use nvtx
    use hydro_device, only: cmpdt_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout) :: sim
    integer(kind=4), intent(in) :: ilevel
    real(kind=8), intent(inout) :: mass, ekin, eint, emag, dt

    integer(kind=4) :: head_idx, num_octs
    integer :: num_threads, num_blocks
    real(kind=dp) :: gamma, dx, courant_factor
    real(kind=8), device :: mass_d, ekin_d, eint_d, emag_d, dt_d

    gamma = sim%r%gamma
    dx = sim%r%boxlen/2**ilevel
    dt = dx/sim%r%smallc
    courant_factor = sim%r%courant_factor

    ! host to device
    dt_d = dt
    mass_d = 0d0
    ekin_d = 0d0
    eint_d = 0d0
    emag_d = 0d0

    head_idx = sim%m%head(ilevel)
    num_octs = sim%m%noct(ilevel)
    num_threads = 256
    num_blocks = (num_octs * twotondim + num_threads - 1 ) / num_threads
    call nvtxStartRange("GPU cmpdt", color=0)!green
    call cmpdt_kernel<<<num_blocks, num_threads>>>(grid, uold, head_idx, num_octs, &
         & mass_d, ekin_d, eint_d, emag_d, dt_d, dx, gamma, courant_factor)
    call GPU_Error_Check(__FILE__, __LINE__)
    call nvtxEndRange()

    ! device to host
    dt = dt_d
    mass = mass_d
    ekin = ekin_d
    eint = eint_d
    emag = emag_d

  end subroutine gpu_cmpdt

  !> @brief
  !> Set uold equal to unew on a GPU
  !>
  !> @detail
  !> @param[in] sim : The simulation object
  !> @param[in] ilevel : The refinement level to update
  !>
  subroutine gpu_set_uold(sim, ilevel)
    use nvtx
    use hydro_device, only: set_uold_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    integer, intent(in)::ilevel

    integer(kind=4) :: head_idx, num_octs
    integer :: threadsX_per_block, threadsY_per_block, num_blocks

    head_idx = sim%m%head(ilevel)
    num_octs = sim%m%noct(ilevel)
    threadsX_per_block = 8
    threadsY_per_block = 16
    num_blocks = (num_octs + threadsY_per_block - 1) / threadsY_per_block
    call nvtxStartRange("GPU Set_uold", color=0)!green
    call set_uold_kernel<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(uold, unew, head_idx, num_octs)
    call GPU_Error_Check(__FILE__, __LINE__)
    call nvtxEndRange()

  end subroutine gpu_set_uold

  !> @brief
  !> Set unew equal to uold on a GPU
  !>
  !> @detail
  !> @param[in] sim : The simulation object
  !> @param[in] ilevel : The refinement level to update
  !>
  subroutine gpu_set_unew(sim, ilevel)
    use nvtx
    use hydro_device, only: set_unew_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    integer, intent(in)::ilevel

    integer(kind=4) :: head_idx, num_octs
    integer :: threadsX_per_block, threadsY_per_block, num_blocks

    head_idx = sim%m%head(ilevel)
    num_octs = sim%m%noct(ilevel)
    threadsX_per_block = 8
    threadsY_per_block = 16
    num_blocks = (num_octs + threadsY_per_block - 1) / threadsY_per_block
    call nvtxStartRange("GPU Set_unew", color=0)!green
    call set_unew_kernel<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(uold, unew, head_idx, num_octs)
    call GPU_Error_Check(__FILE__, __LINE__)
    call nvtxEndRange()

  end subroutine gpu_set_unew

  !> @brief
  !> Perform the hydro integration on a GPU
  !>
  !> @detail
  !> Perform the hydro integration on the GPU with the following steps
  !>
  !> @param[in] sim : The simulation object
  !> @param[in] ilevel : The refinement level to update
  !>
  subroutine gpu_godunov(sim, ilevel)
    use nvtx
    use hydro_device, only: hydro_integrator_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    integer, intent(in)::ilevel
    !
    integer(kind=4) :: head_idx, num_subgrids
    integer :: threads_per_block, num_blocks, ngridmax
    real(dp) :: dt, dx, gamma
    integer :: slope, riemann

    if(sim%r%verbose.and.sim%g%myid==1)write(*,'("   Entering gpu_godunov for level ",I2)')ilevel

    head_idx = (sim%m%head(ilevel) - 1) / nsubgridtondim + 1
    num_subgrids = sim%m%noct(ilevel) / nsubgridtondim
    dt = sim%g%dtnew(ilevel)
    dx = sim%r%boxlen/2**ilevel
    gamma = sim%r%gamma
    num_blocks = num_subgrids
    if(nsubgrid == 1)then
       threads_per_block = 64
    else
       threads_per_block = 256
    endif
    ngridmax = sim%m%ngridmax
    slope = sim%r%slope_type
    riemann = sim%r%riemann

    call nvtxStartRange("GPU Godunov", color=0)!green
    call hydro_integrator_kernel<<<num_blocks, threads_per_block>>>(grid, uold, unew, father, nbor, &
         & head_idx, num_subgrids, ngridmax, ilevel, sim%r%levelmin, sim%r%nlevelmax, &
         & gamma, dt/dx, slope, riemann)
    call GPU_Error_Check(__FILE__, __LINE__)
    call nvtxEndRange()

  end subroutine gpu_godunov

  !> @brief
  !> Restriction of fine cells hydro variable into the coarse level
  !>
  !> @detail
  !> Average conservatively the 8 fine children cells hydro variables into the parent coarse cell.
  !>
  !> @param[in] sim : The simulation object
  !> @param[in] ilevel : The refinement level to update
  !>
  subroutine gpu_upload(sim, ilevel)
    use nvtx
    use hydro_device, only: upload_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    integer, intent(in)::ilevel
    !
    integer(kind=4) :: head_idx, num_octs
    integer(kind=4) :: threads_per_block, num_blocks

    head_idx = sim%m%head(ilevel+1)
    num_octs = sim%m%noct(ilevel+1)
    num_blocks = num_octs
    threads_per_block = 128

    call nvtxStartRange("GPU Upload", color=0)!green
    call upload_kernel<<<num_blocks, threads_per_block>>>(grid, father, uold, head_idx, num_octs)
    call GPU_Error_Check(__FILE__, __LINE__)
    call nvtxEndRange()

  end subroutine gpu_upload

  !> @brief
  !> Cooling and polytrope routine
  !>
  !> @detail
  !> @param[in] sim : The simulation object
  !> @param[in] ilevel : The refinement level to update
  !>
  subroutine gpu_cooling(sim, ilevel)
    use nvtx
    use cooling_device, only: cooling_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout) :: sim
    integer, intent(in) :: ilevel

    integer(kind=4) :: head_idx, num_octs
    integer(kind=4) :: threadsX_per_block, threadsY_per_block, num_blocks
    real(kind=8) :: scale_nH, scale_T2, scale_l, scale_d, scale_t, scale_v

    ! Conversion factor from user units to cgs units
    call units(sim%r,sim%g,scale_l,scale_t,scale_d,scale_v,scale_nH,scale_T2)

    head_idx = sim%m%head(ilevel)
    num_octs = sim%m%noct(ilevel)
    threadsX_per_block = 8
    threadsY_per_block = 16
    num_blocks = (num_octs + threadsY_per_block - 1) / threadsY_per_block
    call nvtxStartRange("GPU Cooling", color=0)!green
    call cooling_kernel<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(uold, grid, &
         & head_idx, num_octs, &
         & sim%r%gamma, sim%g%dtnew(ilevel), sim%r%eos_type, sim%r%eos_T2, sim%r%eos_nH, sim%r%eos_index, &
         & scale_T2, scale_nH)
    call GPU_Error_Check(__FILE__, __LINE__)
    call nvtxEndRange()

  end subroutine gpu_cooling

  !> @brief
  !> Perform the hydro integration on a GPU
  !>
  !> @detail
  !> Perform the hydro integration on the GPU with the following steps
  !>
  !> @param[in] sim : The simulation object
  !> @param[in] ilevel : The refinement level to update
  !>
  subroutine gpu_refine(sim, ilevel, nmake, nkill)
    use nvtx
    use refine_device
    use ramses_commons, only: ramses_t
    use cache_commons
    use cache
    type(ramses_t), intent(inout) :: sim
    integer, intent(in) :: ilevel
    integer, intent(out) :: nmake, nkill
    !
    integer(kind=4) :: head_idx, num_octs, num_subgrids
    integer(kind=4) :: head_cache, info
    integer(kind=4) :: num_blocks, num_threads, num_blocks_2, num_threads_2
    integer(kind=4) :: threadsX_per_block, threadsY_per_block
    integer(kind=4) :: new_ifree, old_ifree, new_head, new_tail, new_noct
    integer(kind=4) :: ilev, ind, ibit, ibucket, skip_bit, noct_level

    integer(kind=4), device :: ifree

    ! Wipe clean cache memory for all higher levels
    head_cache = sim%m%head_cache(ilevel+1)
    head_idx = head_cache + sim%r%ngridmax
    num_octs = sim%m%ifree_cache - head_cache
    num_threads = 128
    num_blocks = (num_octs + num_threads - 1) / num_threads
    if (num_octs > 0) then
       call free_hash_kernel<<<num_blocks, num_threads>>>(grid, hash_key, hash_val, sim%m%hash_size, &
            & ckey_max, key_off, head_idx, num_octs)
    endif
    sim%m%ifree_cache = head_cache

    ! Copy host free memory pointer to device variable
    ifree = sim%m%ifree

    ! Create new octs and put them at the end
    head_idx = sim%m%head(ilevel)
    old_ifree = sim%m%ifree
    num_octs = old_ifree - head_idx
    threadsX_per_block = 8
    threadsY_per_block = 16
    num_blocks = (num_octs + threadsY_per_block - 1) / threadsY_per_block
    if (num_octs > 0) then
       call refine_kernel<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(grid, flag1, uold, &
            & ifree, head_idx, num_octs)
    endif

    ! Copy back to host new free memory pointer ifree
    sim%m%ifree = ifree

    ! Compute new octs
    new_ifree = sim%m%ifree
    nmake = new_ifree - old_ifree

    ! Check we have enough memory
    if (new_ifree > sim%r%ngridmax) then
       write(*,*)'No more main memory, increase ngridmax'
       write(*,*)'New octs:', nmake
       stop
    endif

    ! Insert new octs in hash table
    head_idx = old_ifree
    num_octs = new_ifree - old_ifree
    num_threads = 128
    num_blocks = (num_octs + num_threads - 1) / num_threads
    if (num_octs > 0) then
       call insert_hash_kernel<<<num_blocks, num_threads>>>(grid, hash_key, hash_val, sim%m%hash_size, &
            & ckey_max, key_off, head_idx, num_octs)
    end if

    ! Remove old octs by setting lev to zero and free their hash table entry
    do ilev = sim%r%nlevelmax, ilevel+1, -1
       head_idx = sim%m%head(ilev)
       num_octs = sim%m%noct(ilev)
       num_threads = 128
       num_blocks = (num_octs + num_threads - 1) / num_threads
       if (num_octs > 0) then
          call derefine_kernel<<<num_blocks, num_threads>>>(grid, flag1, hash_key, hash_val, sim%m%hash_size, &
               & ckey_max, key_off, head_idx, num_octs)
       endif
    end do

    ! Sort remaining octs per level and per Hilbert key

    ! Compute kernel size and offset
    head_idx = sim%m%head(ilevel+1)
    num_octs = new_ifree - head_idx
    num_threads = 128
    num_blocks = (num_octs + num_threads - 1) / num_threads

    ! Init global swap table
    if (num_octs > 0) then
       call init_global_swap_table_kernel<<<num_blocks, num_threads>>>(swap_global, head_idx, num_octs)
    endif

    ! Sort octs per levels

    ! Compute new head
    new_head = sim%m%tail(ilevel)
    new_head = new_head + 1

    do ilev = ilevel+1, sim%r%nlevelmax

       ! Transfer new head
       sim%m%head(ilev) = new_head

       ! Compute kernel size and offset
       head_idx = sim%m%head(ilev)
       num_octs = new_ifree - head_idx
       num_threads = 128
       num_blocks = (num_octs + num_threads - 1) / num_threads

       new_noct = 0

       if (num_octs > 0) then

          ! Init prefix sum
          call init_prefix_sum_level<<<num_blocks, num_threads>>>(grid, swap_global, prefix_sum, &
               & head_idx, num_octs, ilev)

          ! Compute prefix sum
          call gpu_scan(head_idx, num_octs, new_noct)

          ! Compute new noct
          new_noct = num_octs - new_noct

          ! Compute local swap table
          call compute_local_swap_table<<<num_blocks, num_threads>>>(swap_local, swap_global, prefix_sum, &
               & head_idx, num_octs)

          ! Update global swap table
          call update_global_swap_table<<<num_blocks, num_threads>>>(swap_global, swap_local, &
               & head_idx, num_octs)

       endif

       ! Compute new tail and next head
       new_tail = new_head + new_noct - 1
       new_head = new_tail + 1
       sim%m%noct(ilev) = new_noct
       sim%m%tail(ilev) = new_tail

    end do
    sim%m%noct_used=sim%m%tail(sim%r%nlevelmax)

    ! New pointer to free memory
    sim%m%ifree = new_head
    nkill = new_ifree - sim%m%ifree

    ! Copy back to device
    ifree = sim%m%ifree

    ! Sort Hilbert key within each level
    do ilev = ilevel + 1, sim%r%nlevelmax

       noct_level = sim%m%noct(ilev)

       if (noct_level > 0) then

          do ibit = ilev, 1, -1

             ! Get bit to read from
             skip_bit = ndim*(ilev-ibit)

             ! Compute kernel size and offset
             new_head = sim%m%head(ilev)
             new_noct = noct_level

             ! loop over buckets
             do ibucket = 1, twotondim - 1

                ! Compute kernel size and offset
                head_idx = new_head
                num_octs = new_noct
                num_threads = 128
                num_blocks = (num_octs + num_threads - 1) / num_threads

                if (num_octs > 0) then

                   ! Init prefix sum
                   call init_prefix_sum_bit<<<num_blocks, num_threads>>>(grid, swap_global, prefix_sum, &
                        & head_idx, num_octs, skip_bit, ibucket - 1)

                   ! Compute prefix sum
                   call gpu_scan(head_idx, num_octs, new_noct)

                   ! Compute local swap table
                   call compute_local_swap_table<<<num_blocks, num_threads>>>(swap_local, swap_global, prefix_sum, &
                        & head_idx, num_octs)

                   ! Update global swap table
                   call update_global_swap_table<<<num_blocks, num_threads>>>(swap_global, swap_local, &
                        & head_idx, num_octs)

                   ! Compute new head and noct
                   new_head = head_idx + num_octs - new_noct

                endif

             end do
          end do
       endif
    end do

    ! Compute kernel size and offset
    head_idx = sim%m%head(ilevel + 1)
    new_ifree = sim%m%ifree
    num_octs = new_ifree - head_idx
    num_threads = 128
    num_blocks = (num_octs + num_threads - 1) / num_threads

    ! Out-of-place sort of grid, flag1 and uold using swap table
    if (num_octs > 0) then
       call sort_gather_grid<<<num_blocks, num_threads>>>(flag2, grid, swap_global, head_idx, num_octs)
       call sort_scatter_grid<<<num_blocks, num_threads>>>(grid, flag2, head_idx, num_octs)
       call sort_gather_flag<<<num_blocks, num_threads>>>(flag2, flag1, swap_global, head_idx, num_octs)
       call sort_scatter_flag<<<num_blocks, num_threads>>>(flag1, flag2, head_idx, num_octs)
       call sort_gather_hydro<<<num_blocks, num_threads>>>(unew, uold, swap_global, head_idx, num_octs)
       call sort_scatter_hydro<<<num_blocks, num_threads>>>(uold, unew, head_idx, num_octs)
    endif

    ! Update hash table
    if (num_octs > 0) then
       call update_hash_kernel<<<num_blocks, num_threads>>>(grid, hash_key, hash_val, sim%m%hash_size, &
            & ckey_max, key_off, head_idx, num_octs)
    end if

    info = cudaDeviceSynchronize()
    call m_timer('cache','start')

    ! Update father index array (they should always exist without MPI)
    if (num_octs > 0) then
       call update_father_array<<<num_blocks, num_threads>>>(grid, father, hash_key, hash_val, sim%m%hash_size, &
            & ckey_max, key_off, head_idx, num_octs)
    endif

    ! Update nbor index array level by level
    ! If nbor is absent, make a ghost oct in the cache and insert in hash table

    ! Compute new cache head
    new_head = sim%m%tail_cache(ilevel) + 1

    do ilev = ilevel + 1, sim%r%nlevelmax

       noct_level = sim%m%noct(ilev)
       sim%m%head_cache(ilev) = new_head

       new_noct = 0

       if (noct_level > 0) then

          ! Compute kernel size and offset
          head_idx = (sim%m%head(ilev) - 1) / nsubgridtondim + 1
          num_subgrids = noct_level / nsubgridtondim
          num_threads = 128
          num_blocks = (num_subgrids + num_threads - 1) / num_threads

          ! Loop over 27 neighbors
          do ind = 1, subgridsize

             ! Get nbor index from hash table
             call update_nbor_array<<<num_blocks, num_threads>>>(nbor, grid, hash_key, hash_val, sim%m%hash_size, &
                  & ckey_max, key_off, box_ckey_min, box_ckey_max, periodic, head_idx, num_subgrids, ind)

             ! Init prefix sum (count non existing nbor index)
             call init_prefix_sum_nbor<<<num_blocks, num_threads>>>(nbor, prefix_sum, head_idx, num_subgrids, ind)

             ! Compute prefix sum
             call gpu_scan(head_idx, num_subgrids, new_noct)

             ! Transfer head index of first free cache oct from device
             head_cache = sim%r%ngridmax + sim%m%ifree_cache
             new_ifree = sim%m%ifree_cache + new_noct
             num_threads_2 = 128
             num_blocks_2 = (new_noct + num_threads - 1) / num_threads

             if (new_noct > 0) then

                ! Check we have enough memory
                if (new_ifree > sim%r%ncachemax) then
                   write(*,*)'No more cache memory, increase ncachemax'
                   write(*,*)'New cache octs:', new_noct, 'ind:', ind
                   stop
                endif

                ! Compute cache swap table
                call compute_cache_swap_table<<<num_blocks, num_threads>>>(swap_local, prefix_sum, head_idx, num_subgrids)

                ! Make new ghost octs in cache
                call make_cache_octs<<<num_blocks_2, num_threads_2>>>(grid, flag1, uold, swap_local, father, nbor, &
                     & hash_key, hash_val, sim%m%hash_size, ckey_max, key_off, box_ckey_min, box_ckey_max, periodic, &
                     & head_cache, new_noct, ind)

                ! Insert new octs in hash table
                call insert_hash_kernel<<<num_blocks_2, num_threads_2>>>(grid, hash_key, hash_val, sim%m%hash_size, &
                     & ckey_max, key_off, head_cache, new_noct)

             end if

             ! Store new first free cache oct 
             sim%m%ifree_cache = new_ifree

          end do
          ! End loop over 27 nbors

       end if

       ! Compute new cache tail and next cache head
       new_tail = new_head + new_noct - 1
       new_head = new_tail + 1
       sim%m%noct_cache(ilev) = new_noct
       sim%m%tail_cache(ilev) = new_tail

    end do
    ! End loop over levels

  end subroutine gpu_refine

  !> @brief
  !> Initial step for flagging cells for refinements
  !>
  !> @detail
  !> A cell is flag if it contains a child grid with at least one flagged or refined cell
  !>
  subroutine gpu_init_flag(sim, ilevel, nflag)
    use nvtx
    use flag_device, only: reset_flag1_kernel, init_flag_kernel, count_flag1_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout) :: sim
    integer, intent(in) :: ilevel
    integer, intent(inout) :: nflag

    integer(kind=4) :: head_idx, num_octs
    integer :: threadsX_per_block, threadsY_per_block, num_threads, num_blocks
    integer(kind=8) :: nflag_h
    integer(kind=8), device :: nflag_d

    head_idx = sim%m%head(ilevel)
    num_octs = sim%m%noct(ilevel)
    threadsX_per_block = 8
    threadsY_per_block = 16
    num_blocks = (num_octs + threadsY_per_block - 1) / threadsY_per_block
    if (num_octs > 0) then
       call reset_flag1_kernel<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(flag1, head_idx, num_octs)
    endif

    head_idx = sim%m%head(ilevel+1)
    num_octs = sim%m%noct(ilevel+1)
    num_threads = 128
    num_blocks = (num_octs + num_threads - 1) / num_threads
    if (num_octs > 0) then
       call init_flag_kernel<<<num_blocks, num_threads>>>(flag1, grid, father, head_idx, num_octs)
    endif

    nflag_h = 0
    nflag_d = nflag_h

    head_idx = sim%m%head(ilevel)
    num_octs = sim%m%noct(ilevel)
    num_threads = 256
    num_blocks = (num_octs * twotondim + num_threads - 1 ) / num_threads
    if (num_octs > 0) then
       call count_flag1_kernel<<<num_blocks, num_threads>>>(flag1, head_idx, num_octs, nflag_d)
    endif

    nflag_h = nflag_d
    nflag = int(nflag_h, kind=4)

  end subroutine gpu_init_flag

  !> @brief
  !> Enforce entire oct to have flag = 1.
  !>
  !> @detail
  !> If one cell is flagged, then flag the entire oct.
  !>
  subroutine gpu_enforce_subgrid(sim, ilevel)
    use nvtx
    use flag_device, only: enforce_subgrid_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout) :: sim
    integer, intent(in) :: ilevel

    integer(kind=4) :: head_idx, num_octs
    integer :: num_threads, num_blocks

    head_idx = sim%m%head(ilevel)
    num_octs = sim%m%noct(ilevel)
    num_threads = 128
    num_blocks = (num_octs + num_threads - 1) / num_threads
    if (num_octs > 0) then
       call enforce_subgrid_kernel<<<num_blocks, num_threads>>>(flag1, head_idx, num_octs)
    endif

  end subroutine gpu_enforce_subgrid

  !> @brief
  !> User defined refinement criteria
  !>
  !> @detail
  !> Apply several user-defined refinement criteria to flag cells
  !>
  subroutine gpu_user_flag(sim, ilevel, nflag)
    use nvtx
    use hydro_device, only: hydro_flag_kernel
    use flag_device, only: count_flag1_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout) :: sim
    integer, intent(in) :: ilevel
    integer, intent(inout) :: nflag

    integer(kind=4) :: head_idx, num_octs
    integer :: threadsX_per_block, threadsY_per_block, num_threads, num_blocks
    real(kind=dp) :: gamma, err_grad_d, err_grad_p, floor_d, floor_p
    integer(kind=8) :: nflag_h
    integer(kind=8), device :: nflag_d

    gamma = sim%r%gamma
    err_grad_d = sim%r%err_grad_d
    err_grad_p = sim%r%err_grad_p
    floor_d = sim%r%floor_d
    floor_p = sim%r%floor_p

    head_idx = sim%m%head(ilevel)
    num_octs = sim%m%noct(ilevel)
    threadsX_per_block = 8
    threadsY_per_block = 16
    num_blocks = (num_octs + threadsY_per_block - 1) / threadsY_per_block
    if(num_octs > 0)then
       call hydro_flag_kernel<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(flag1, grid, nbor, uold, &
            & head_idx, num_octs, gamma, err_grad_d, err_grad_p, floor_d, floor_p)
    endif

    nflag_h = 0
    nflag_d = nflag_h

    head_idx = sim%m%head(ilevel)
    num_octs = sim%m%noct(ilevel)
    num_threads = 256
    num_blocks = (num_octs * twotondim + num_threads - 1 ) / num_threads
    if (num_octs > 0) then
       call count_flag1_kernel<<<num_blocks, num_threads>>>(flag1, head_idx, num_octs, nflag_d)
    endif

    nflag_h = nflag_d
    nflag = int(nflag_h, kind=4)

  end subroutine gpu_user_flag

  !> @brief
  !> Smooth refinement map
  !>
  !> @detail
  !> Set flag2 to zero, count neighbors in flag2 and set flag1 to 1 if enough neighbors.
  !>
  subroutine gpu_smooth_flag(sim, ilevel, nflag)
    use nvtx
    use flag_device, only: count_neighbors, flag_count_kernel, count_flag1_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    integer, intent(in) :: ilevel
    integer, intent(inout) :: nflag

    integer(kind=4) :: head_idx, num_octs
    integer :: threadsX_per_block, threadsY_per_block, num_threads, num_blocks, idim
    integer(kind=8) :: nflag_h
    integer(kind=8), device :: nflag_d

    head_idx = sim%m%head(ilevel)
    num_octs = sim%m%noct(ilevel)
    threadsX_per_block = 8
    threadsY_per_block = 16
    num_blocks = (num_octs + threadsY_per_block - 1) / threadsY_per_block

    if(num_octs > 0)then
       do idim = 1, ndim ! Loop over steps
          call count_neighbors<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(flag2, flag1, nbor, &
               & head_idx, num_octs)
          call flag_count_kernel<<<num_blocks, dim3(threadsX_per_block,threadsY_per_block,1)>>>(flag1, flag2, &
               & head_idx, num_octs, n_nbor(idim))
       end do
    endif

    nflag_h = 0
    nflag_d = nflag_h

    head_idx = sim%m%head(ilevel)
    num_octs = sim%m%noct(ilevel)
    num_threads = 256
    num_blocks = (num_octs * twotondim + num_threads - 1 ) / num_threads
    if (num_octs > 0) then
       call count_flag1_kernel<<<num_blocks, num_threads>>>(flag1, head_idx, num_octs, nflag_d)
    endif

    nflag_h = nflag_d
    nflag = int(nflag_h, kind=4)

  end subroutine gpu_smooth_flag

  !> @brief
  !> Enforce refinemnt rules
  !>
  !> @detail
  !> Set flag1 to zero if not enough existing neighboring grids
  !>
  subroutine gpu_enforce_rules(sim, ilevel)
    use nvtx
    use flag_device, only: enforce_rules
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    integer, intent(in)::ilevel

    integer(kind=4) :: head_idx, num_octs
    integer :: num_threads, num_blocks, ngridmax

    head_idx = sim%m%head(ilevel)
    num_octs = sim%m%noct(ilevel)
    ngridmax = sim%r%ngridmax

    num_threads = 128
    num_blocks = (num_octs + num_threads - 1) / num_threads
    if(num_octs > 0)then
       call enforce_rules<<<num_blocks, num_threads>>>(flag1, nbor, head_idx, num_octs, ngridmax)
    endif

  end subroutine gpu_enforce_rules

  !> @brief
  !> Perform a prefix sum (or a scan) on the input integer array data
  !>
  !> @detail
  !> Perform a prefix scum only starting from index head_idx and over num_octs elements.
  !>
  subroutine gpu_scan(head_idx, num_octs, total_sum)
    integer(kind=4) :: head_idx
    integer(kind=4) :: num_octs
    integer(kind=4) :: total_sum
    !
    integer(kind=4) :: block_size, grid_size_0, grid_size_1, grid_size_2
    integer(kind=4) :: offset, size
    integer(kind=4) :: num_max_0, num_max_1, num_max_2

    integer(kind=4), device :: total_sum_d

    block_size = 256
    num_max_0 = block_size**2
    num_max_1 = block_size**3
    num_max_2 = huge(1_4)

    if(num_octs <= num_max_0)then

       ! Works only for arrray size smaller or equal than 256^2=65'536
       grid_size_0 = (num_octs + block_size - 1) / block_size
       call block_scan<<<grid_size_0, block_size>>>(prefix_sum, head_idx, num_octs, partial_sums_0, total_sum_d)
       if (grid_size_0 > 1) then
          call block_scan<<<1, grid_size_0>>>(partial_sums_0, 1, grid_size_0)
          offset = head_idx + block_size
          size = num_octs - block_size
          call uniform_add<<<grid_size_0 - 1, block_size>>>(prefix_sum, offset, size, partial_sums_0, total_sum_d)
       end if

    else if(num_octs <= num_max_1)then

       ! Works only for arrray size smaller or equal than 256^3=16'777'216
       grid_size_0 = (num_octs + block_size - 1) / block_size
       call block_scan<<<grid_size_0, block_size>>>(prefix_sum, head_idx, num_octs, partial_sums_0)
       grid_size_1 = (grid_size_0 + block_size - 1) / block_size
       call block_scan<<<grid_size_1, block_size>>>(partial_sums_0, 1, grid_size_0, partial_sums_1)
       if (grid_size_1 > 1) then
          call block_scan<<<1, grid_size_1>>>(partial_sums_1, 1, grid_size_1)
          offset = 1 + block_size
          size = grid_size_0 - block_size
          call uniform_add<<<grid_size_1 - 1, block_size>>>(partial_sums_0, offset, size, partial_sums_1)
       end if
       offset = head_idx + block_size
       size = num_octs - block_size
       call uniform_add<<<grid_size_0 - 1, block_size>>>(prefix_sum, offset, size, partial_sums_0, total_sum_d)

    else if(num_octs <= num_max_2)then

       ! Works only for arrray size smaller or equal than huge(1_4)=2'147'483'647
       grid_size_0 = (num_octs + block_size - 1) / block_size
       call block_scan<<<grid_size_0, block_size>>>(prefix_sum, head_idx, num_octs, partial_sums_0)
       grid_size_1 = (grid_size_0 + block_size - 1) / block_size
       call block_scan<<<grid_size_1, block_size>>>(partial_sums_0, 1, grid_size_0, partial_sums_1)
       grid_size_2 = (grid_size_1 + block_size - 1) / block_size
       call block_scan<<<grid_size_2, block_size>>>(partial_sums_1, 1, grid_size_1, partial_sums_2)
       if (grid_size_2 > 1) then
          call block_scan<<<1, grid_size_2>>>(partial_sums_2, 1, grid_size_2)
          offset = 1 + block_size
          size = grid_size_1 - block_size
          call uniform_add<<<grid_size_2 - 1, block_size>>>(partial_sums_1, offset, size, partial_sums_2)
       end if
       offset = 1 + block_size
       size =  grid_size_0 - block_size
       call uniform_add<<<grid_size_1 - 1, block_size>>>(partial_sums_0, offset, size, partial_sums_1)
       offset = head_idx + block_size
       size = num_octs - block_size
       call uniform_add<<<grid_size_0 - 1, block_size>>>(prefix_sum, offset, size, partial_sums_0, total_sum_d)

    else

       write(*,*)'Too many octs for prefix sum...'
       stop

    endif

    total_sum = total_sum_d

  end subroutine gpu_scan

  !> @brief
  !> Initialize the hash table
  !>
  !> @detail
  !> Loop over all existing octs and insert them in the hash table
  !>
  !> @param[in] sim : The simulation object
  !>
  subroutine gpu_reset_hash(sim)
    use nvtx
    use refine_device, only: insert_hash_kernel
    use ramses_commons, only: ramses_t
    type(ramses_t), intent(inout)::sim
    !
    integer(kind=4) :: head_idx, num_octs
    integer :: num_blocks, threads_per_block

    ! Allocate hash tables for the first time
    if(allocated(hash_key))deallocate(hash_key)
    if(allocated(hash_val))deallocate(hash_val)
    allocate(hash_key(1:sim%m%hash_size))
    allocate(hash_val(1:sim%m%hash_size))
    hash_key = 0
    hash_val = 0

    ! Insert entire grid in the device hash table
    head_idx = 1
    num_octs = sim%m%ifree - 1
    if (num_octs > 0) then
       threads_per_block = 128
       num_blocks = (num_octs + threads_per_block - 1) / threads_per_block
       call insert_hash_kernel<<<num_blocks, threads_per_block>>>(grid, hash_key, hash_val, sim%m%hash_size, ckey_max, key_off, head_idx, num_octs)
    endif

    ! Insert entire cache in the device hash table
    head_idx = sim%r%ngridmax + 1
    num_octs = sim%m%ifree_cache - 1
    if (num_octs > 0) then
       threads_per_block = 128
       num_blocks = (num_octs + threads_per_block - 1) / threads_per_block
       call insert_hash_kernel<<<num_blocks, threads_per_block>>>(grid, hash_key, hash_val, sim%m%hash_size, ckey_max, key_off, head_idx, num_octs)
    endif

  end subroutine gpu_reset_hash

  !###########################################################
  !###########################################################
  !###########################################################
  !###########################################################

end module gpu_runner
