! =========================================================================
!> @brief
!> Compute fnv1a hash
!>
attributes(device) pure function fnv1a(key)
  integer(kind=8), intent(in) :: key
  integer(kind=8) :: fnv1a
  integer :: j
  integer(kind=8) :: k, hash
  integer(kind=8) :: fnv32_basis = 2166136261_8
  integer(kind=8) :: fnv32_prime = 16777619_8

  hash = fnv32_basis

  do j = 0, 3
     k = ibits(key, 8*j, 8)
     hash = ieor(hash, k)
     hash = hash * fnv32_prime
     hash = ibits(hash, 0, 32)
  end do

  fnv1a = hash

end function fnv1a
! =========================================================================

! =========================================================================
!> @brief
!> Insert new key/value pair in hash table
!>
attributes(device) subroutine hash_set(hash, key, val)
  use gpu_runner, only: hash_gpu
  implicit none
  type(hash_gpu) :: hash
  integer(kind=8) :: key
  integer(kind=4) :: val

  integer(kind=8) :: ibucket, prev

  ! Compute bucket idx from hash function
  ibucket = MOD(fnv1a(key), hash%size) + 1

  ! Insert value using linear probing
  do
     prev = atomiccas(hash%key(ibucket), 0, key)
     if((prev == 0) .or. (prev == key))then
        hash%val(ibucket) = val
        return
     endif
     ibucket = MOD(ibucket, hash%size) + 1 
  end do

end subroutine hash_set
! =========================================================================

! =========================================================================
!> @brief
!> Free existing key in hash table
!>
attributes(device) subroutine hash_free(hash, key)
  use gpu_runner, only: hash_gpu
  implicit none
  type(hash_gpu) :: hash
  integer(kind=8) :: key

  integer(kind=8) :: ibucket

  ! Compute bucket idx from hash function
  ibucket = MOD(fnv1a(key), hash%size) + 1

  ! Delete value using linear probing
  ! Note that key is left in the hash table
  do
     if(hash%key(ibucket) == key)then
        hash%val(ibucket) = 0
        return
     endif
     if(hash%key(ibucket) == 0)then
        return
     endif
     ibucket = MOD(ibucket, hash%size) + 1
  end do

end subroutine hash_free
! =========================================================================

! =========================================================================
!> @brief
!> Update val of existing key in hash table
!>
attributes(device) subroutine hash_update(hash, key, val)
  use gpu_runner, only: hash_gpu
  implicit none
  type(hash_gpu) :: hash
  integer(kind=8) :: key

  integer(kind=8) :: ibucket

  ! Compute bucket idx from hash function
  ibucket = MOD(fnv1a(key), hash%size) + 1

  ! Update value using linear probing
  do
     if(hash%key(ibucket) == key)then
        hash%val(ibucket) = val
        return
     endif
     if(hash%key(ibucket) == 0)then
        return
     endif
     ibucket = MOD(ibucket, hash%size) + 1
  end do

end subroutine hash_update
! =========================================================================

! =========================================================================
!> @brief
!> Get value from key in hash table
!>
attributes(device) function hash_get(hash, key)
  use gpu_runner, only: hash_gpu
  implicit none
  type(hash_gpu) :: hash
  integer(kind=8) :: key
  integer(kind=4) :: hash_get

  integer(kind=8) :: ibucket

  ! Compute bucket idx from hash function
  ibucket = MOD(fnv1a(key), hash%size) + 1

  ! Read value using linear probing
  do
     if(hash%key(ibucket) == key)then
        hash_get = hash%val(ibucket)
        return
     endif
     if(hash%key(ibucket) == 0)then
        hash_get = 0
        return
     endif
     ibucket = MOD(ibucket, hash%size) + 1
  end do

end function hash_get
! =========================================================================
