!================================================================
!================================================================
!================================================================
!================================================================

attributes(device) function hilbert_key(ix, level) result(hkey)
  use amr_parameters, only: nhilbert, ndim, twotondim
  use hilbert, only: left_shift, right_shift
  implicit none
  integer,                            intent(in) :: level
  integer(kind=4), dimension(1:ndim), intent(in) :: ix
  integer(kind=8) :: hkey

  integer(kind=8),parameter,dimension(0:95)::next_digits_diagram=(/&
       &   0, 1, 3, 2, 7, 6, 4, 5,&
       &   0, 7, 1, 6, 3, 4, 2, 5,&
       &   0, 3, 7, 4, 1, 2, 6, 5,&
       &   2, 3, 1, 0, 5, 4, 6, 7,&
       &   4, 3, 5, 2, 7, 0, 6, 1,&
       &   6, 5, 1, 2, 7, 4, 0, 3,&
       &   4, 7, 3, 0, 5, 6, 2, 1,&
       &   6, 7, 5, 4, 1, 0, 2, 3,&
       &   2, 5, 3, 4, 1, 6, 0, 7,&
       &   2, 1, 5, 6, 3, 0, 4, 7,&
       &   4, 5, 7, 6, 3, 2, 0, 1,&
       &   6, 1, 7, 0, 5, 2, 4, 3 /)

  integer(kind=4),parameter,dimension(0:95)::next_state_diagram=(/&
       &   1, 2, 3, 2, 4, 5, 3, 5,&
       &   2, 6, 0, 7, 8, 8, 0, 7,&
       &   0, 9,10, 9, 1, 1,11,11,&
       &   6, 0, 6,11, 9, 0, 9, 8,&
       &  11,11, 0, 7, 5, 9, 0, 7,&
       &   4, 4, 8, 8, 0, 6,10, 6,&
       &   5, 7, 5, 3, 1, 1,11,11,&
       &   6, 1, 6,10, 9, 4, 9,10,&
       &  10, 3, 1, 1,10, 3, 5, 9,&
       &   4, 4, 8, 8, 2, 7, 2, 3,&
       &   7, 2,11, 2, 7, 5, 8, 5,&
       &  10, 3, 2, 6,10, 3, 4, 4 /)

  ! Compute 3-integer hilbert keys from the cartesian keys ix

  integer(kind=4) :: cstate, sdigit, ind
  integer         :: ibit, add_digit, idim

  cstate = 0
  hkey = 0

  do ibit = level - 1, 0, -1
     hkey = ISHFT(hkey, left_shift)
     hkey = ISHFT(hkey, right_shift)

     sdigit=0
     do idim = 1, ndim
        add_digit = 2 ** (ndim - idim)
        if(btest(ix(idim),ibit)) sdigit = sdigit + add_digit
     end do

     ind = cstate * twotondim + sdigit
     cstate = next_state_diagram(ind)
     hkey = hkey + next_digits_diagram(ind)
  enddo

end function hilbert_key

!================================================================
!================================================================
!================================================================
!================================================================
