# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: cphyc/openmpi-iap

pipelines:
  default:
    - step:     # Build hydro2d
        name: hydro2d version
        script:
        - bash tests/build.hydro2d.sh
    - step:     # Build cosmo3d
        name: cosmo3d version
        script:
        - bash tests/build.cosmo3d.sh
